### ISSUE TITLE
Cumulus crashes alot on Mi Box

### ISSUE THREAD

**Issue by joq3** [Fleker/CumulusTV#199] opened 2016-12-05 14:01 UTC
Hi,

I have a Mi Box (international) with Android TV 6.0.1. Using latest Live channels app and 1.6.7 Cumulus TV.
I have a .m3u file containing 120 channels which I open via ES File Explorer and open with Cumulus TV. This works. But when I go to the Live channels app it will freeze up when I load the channels, the parsing channels will lock up and be a black screen.
Eventually I can restart Live channels and 1 in 10 times I am able to watch a channel, but it almost always crashes with the result that Android asks me if I want to close Cumulus TV.

I also get an error about loading screen not showing but its loading in the background anyway.

Any ideas?

**Comment by Fleker** [comment] 2016-12-06 05:11
I'll have to look at the crash logs to see why.

Is this happening when you're trying to sync channels? Is there a error
with the app not responding?

On Dec 5, 2016 9:01 AM, "joq3" <notifications@github.com> wrote:

Hi,

I have a Mi Box (international) with Android TV 6.0.1. Using latest Live
channels app and 1.6.7 Cumulus TV.
I have a .m3u file containing 120 channels which I open via ES File
Explorer and open with Cumulus TV. This works. But when I go to the Live
channels app it will freeze up when I load the channels, the parsing
channels will lock up and be a black screen.
Eventually I can restart Live channels and 1 in 10 times I am able to watch
a channel, but it almost always crashes with the result that Android asks
me if I want to close Cumulus TV.

I also get an error about loading screen not showing but its loading in the
background anyway.

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Fleker/CumulusTV/issues/199>, or mute the thread

**Comment by JeanPrendnote** [comment] 2016-12-18 06:50
same here :(

**Comment by Fleker** [comment] 2016-12-18 06:54
I just published a new beta 1.6.8 that should fix a lot of the crashing.

-Nick

**Comment by JeanPrendnote** [comment] 2016-12-18 17:03
i can't use it, it keep crashing, i have never managed to get the video various crash and error messages.

Mibox, 1.6.8. M3u 130channles (some down) with .ts files.

Work fine in the android tv app "IPTV" from google play.

**Comment by JeanPrendnote** [comment] 2016-12-18 17:06
Work fine in the android tv app "IPTV" from google play.

here my m3u : [ok.zip](https://github.com/Fleker/CumulusTV/files/659533/ok.zip)

**Comment by Fleker** [comment] 2016-12-18 17:58
I'll take another look at crash reports and your data. Are you submitting
crash reports through Google Play? Can you make a brief mention in the
description so I can identify your specific crash?

-Nick

**Comment by nicco** [comment] 2017-01-07 14:34
I'm also getting crashes should I start to submit them thru google play too?

**Comment by Fleker** [comment] 2017-01-07 17:56
I have another service to provide automatic crash reports, so that isn't
necessary. But reporting crashes can also include a brief description
adding additional context to reproduce.

**Comment by Fleker** [comment] 2017-01-11 02:16
Should be fixed on the latest beta

**Comment by Fleker** [comment] 2017-01-27 00:11
Most of these issues should be fixed. For anything more specific, a new issue should be created.

**Closed by Fleker** 2017-01-27 00:11 UTC
Labels: bug
