### ISSUE TITLE
Error opening 1.6.1

### ISSUE THREAD

**Issue by josuearisty** [Fleker/CumulusTV#175] opened 2016-09-06 04:47 UTC
When I open cumulus on android TV im getting:
Something isnt working: loadRows has no activity!

**Comment by Fleker** [comment] 2016-09-06 12:50
Is that consistent? What device is that on? I've occasionally seen that
happen but I have had trouble reproducing it.

**Comment by drauks** [comment] 2016-09-06 14:58
Happens to me too on the Nvidia Shield. Reinstalled, still happens consistently.

**Comment by dgaussin** [comment] 2016-09-06 16:52
Samedi message hère on NVIDIA Shield too.

**Comment by Fleker** [comment] 2016-09-06 16:53
Okay I'll take a look at this bug and it'll be fixed soon. In the meantime you should be able to revert to an earlier version.

**Comment by josuearisty** [comment] 2016-09-06 16:58
I have a Nexus Player! I re-installed and still the same. 

Thanks nick!

**Comment by danielsamwel** [comment] 2016-09-06 19:48
Getting the same issue on NVIDIA Shield. Uninstall and reinstall did not fix.

**Comment by Fleker** [comment] 2016-09-07 21:56
Have updated the app in the Play Store. Is there any change for you?

**Comment by josuearisty** [comment] 2016-09-08 01:09
@Nick I did! I updated the app in the playstore but still the same.

**Comment by josuearisty** [comment] 2016-09-08 01:21
i didnt know there was an update! Im trying now, I will let you know!

**Comment by Fleker** [comment] 2016-09-16 05:02
Is the original issue still happening?

**Comment by josuearisty** [comment] 2016-09-16 14:40
@Nick, I will try when I get home, I have been some days without fast internet, so Im not watching iptv these days. But I will try anyway and I will let you know.

**Comment by josuearisty** [comment] 2016-09-16 14:48
@Nick, I forgot to tell you that with version 1.6.1, I added this xml epg to a channel: http://epg.entutele.com/feed.xml, and it disappeared from the channels list.

**Comment by Fleker** [comment] 2016-09-16 15:21
Thanks for the report.
Let me know about the fragment issue. I think it's fixed, so I'd like to
close the issue.

**Comment by josuearisty** [comment] 2016-09-17 03:52
@Nick, where is the 1.6.2 update? I just can find the 1.6.1 and I alredy reported the issues.

**Comment by Fleker** [comment] 2016-09-17 15:35
Ah, I never got around to uploading it because there were some issues with
a test and thats something I hope to tackle today.

But it is available in the beta track of the Google Play Store.

**Closed** 2016-11-03 23:50 UTC
