### ISSUE TITLE
Android M Preview crashes

### ISSUE THREAD

**Issue by bgiesing** [Fleker/CumulusTV#31] opened 2015-08-15 16:42 UTC
On the M preview, it crashes on basically everything.

## What works
- App loads
- Can connect to Drive

## What doesn't
- Creating station
  - From suggested
  - From Create plugin
  - From JSON File
- Loading station
- View streams

---

I know that this is a preview, I just want to make sure you will have it ready in time for release! @Fleker, anything I can do to help?

**Comment by Fleker** [comment] 2015-08-15 17:16
Thanks for letting me know. I haven't tested it on M yet

**Comment by Fleker** [comment] 2015-08-15 17:17
If you could compile the app and get the stack traces from crashes that
would be a great help. But I have crashlytics running so I get notified of
every crash. It should give me more insight into the problems even if I
can't reproduce them personally.

**Comment by bgiesing** [comment] 2015-08-15 17:23
That's the one thing I can't do! :frowning: My machine is under-powered and it's Windows!

**Comment by Fleker** [comment] 2015-08-15 17:27
That's okay. I'll be getting crash reports either way.

**Comment by Fleker** [comment] 2015-08-16 05:38
It looks like I've gotten a few crash reports from devices not on Lollipop. I don't know exactly which bugs you've run into, but I think I've created workarounds for each one. 

A lot of these issues seem to be related to JSON crashing and not correctly executing further commands causing null pointers.

`1.2.4` will be released soon. Unfortunately I'll be at a conference this week and won't have much free time, but I'll be able to check the crash logs.

**Comment by bgiesing** [comment] 2015-08-16 12:51
Seems to work now!

**Comment by Fleker** [comment] 2015-08-16 13:36
Does it just not crash or not report any errors?

**Comment by bgiesing** [comment] 2015-08-16 13:38
It doesn't crash and everything plays fine.

**Comment by Fleker** [comment] 2015-08-16 16:05
Great!

**Closed by Fleker** 2015-08-16 16:05 UTC
